parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: docapp
    database_user: sonata
    database_password: asucse360
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 274aea36a65c0bf329e5edf23c8e137172838a7a
    database_path: null
