parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: '3306'
    database_name: docapp
    database_user: sonata
    database_password: asucse360
    mailer_transport: smtp
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: cory.siebler@gmail.com
    mailer_password: tphcpugeyskixyjf
    mailer_replyTo: cory.siebler@gmail.com
    locale: en
    secret: 274aea36a65c0bf329e5edf23c8e137172838a7a
    database_path: null