sonata_appointment:
    resource: "@SonataAppointmentBundle/Controller/"
    type:     annotation
    prefix:   /appointment

sonata_health:
    resource: "@SonataHealthBundle/Controller/"
    type:     annotation
    prefix:   /health

sonata_security:
    resource: "@SonataSecurityBundle/Controller/"
    type:     annotation
    prefix:   /security

sonata_user:
    resource: "@SonataUserBundle/Controller/"
    type:     annotation
    prefix:   /user

sonata_website:
    resource: "@SonataWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile