jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SITE-ADMIN:  [ROLE_DOCTOR, ROLE_PATIENT, ROLE_ADMIN, ROLE_EMT]
        ROLE_DOCTOR:      ROLE_USER
        ROLE_PATIENT:     ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_EMT:         ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: sonata_user.listener.login_success
            logout:       true
            anonymous:    true

    acl:
      connection: default

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, role: ROLE_ADMIN }
        - { path: ^/user/site-admin, role: ROLE_SITE-ADMIN }
        - { path: ^/user/office-admin, role: ROLE_ADMIN }
        - { path: ^/user/patient, role: ROLE_PATIENT }
        - { path: ^/user/doctor, role: ROLE_DOCTOR }
        - { path: ^/user/nurse, role: ROLE_NURSE }
        - { path: ^/user/emt, role: ROLE_EMT }