services:
    sonata_user.registration.form.type:
        class: Sonata\UserBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: sonata_user_registration }

    sonata_user.listener.registration:
        class: Sonata\UserBundle\EventListener\RegistrationListener
        arguments: [ '@doctrine.orm.default_entity_manager', '@router' ]
        tags:
            - { name: kernel.event_subscriber }