<?php

namespace Sonata\HealthBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BloodPressureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloodPressureRepository extends EntityRepository
{
}
